name: 1.0$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPublish: 'WpfUI'
  PublishPath: '$(Build.ArtifactStagingDirectory)'
  SolutionName: 'MLH.TODO.sln'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishAsArtifact'
  displayName: 'Build and save zipped Artifact'
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      buildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Publish.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      FolderToPublish: $(FolderToPublish)
      Publishpath: $(PublishPath)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Zip_And_Save_Artifact.yaml@ALMStuff
